name: Orbit- Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      
      - name: Run tests with Testcontainers (verbose)
        run: ./gradlew test \
             -Dspring.profiles.active=testcontainers \
             --info \
             --stacktrace
